### ISSUE TITLE
Slow rendering 

### ISSUE THREAD

**Issue by Ghassanee** [D10S60948/react-native-range-slider-expo#14]
RangeSlider is rendering slow .
I also tested it in a simple app and it's still slow.
 
 <img src="https://user-images.githubusercontent.com/45521443/123308622-cb811600-d51b-11eb-8f08-d116a0cbb970.gif" width="400" height="790">

Thanks!

**Comment by avishain** [comment]
It is slow because of the responsiveness. Since it waits for the initial layout to happened and then calculated the initial knobs position values according to layout width.
Once the bridge will be destroyed and JSI will take place I assume it will be much faster on Android (ios I assume is already renders fast now).
If you want to try to tackle it now PRs are more than welcome :)
